id: PDAD277B5
initial_creation_type: input
source_metadata:
  title: Ngakchang Shakya Zangpo Series
  language: bo
  description: 'Texts related to the tertön Ngakchang Shakya Zangpo (sngags ''chang
    shākya bzang po, b. 15th century), who is famous for having opened up the ''hidden
    land'' of Yolmo:'
  volume:
    d91a0db7e1af40c6997aa887c2100e64:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: History
created_at: '2022-03-01T00:59:21.984259'
last_modified_at: '2022-03-01T00:59:21.984261'
statistics:
  total_words: 9076
  total_non_words: 800
quality:
  non_words_ratio: 0.09
